### ISSUE TITLE
noob here. get this error when i "grunt deploy"

### ISSUE THREAD

**Issue by dackdel** [blakecarroll/particle-saga#5]
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/nodejs/grunt-cli/bin/grunt:8:14)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)

**Comment by dackdel** [comment]
that was on ubuntu ^

on a mac i get this > 
Running "coffee:compile" (coffee) task
>> source/coffee/ImageTarget.coffee:11:11: error: Can't call super with @params in derived class constructors
>>     super(@targetData, options)
>>           ^^^^^^^^^^^
>> In file: source/coffee/ImageTarget.coffee
>> On line: 10
>>     super(@targetData, options)
>>           ^
Warning: CoffeeScript failed to compile. Use --force to continue.

Aborted due to warnings.

when i do grunt deploy
